proyectofinal/lovisto/urls.py
from django.urls import path
from lovisto import views

urlpatterns = [
    path('', views.index),
    path('aportaciones', views.pag_aportaciones),
    path('logout', views.logout_view, name='logout'),
    path('informacion', views.informacion, name='informacion'),
    path('<str:llave>-<str:id>', views.aportacion),
    path('pag_usuario', views.pag_usuario),
    path('<str:recurso>', views.error),


]

proyectofinal/proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login


urlpatterns = [
    path('lovisto/', include('lovisto.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
]

proyectofinal/lovisto/models.py
from django.db import models
# Create your models here.


class Usuario(models.Model):
    usuario = models.CharField(max_length=20)
    tema = models.CharField(max_length=15, default="claro")

    def __str__(self):
        return self.usuario

class RecursoN(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=30)
    imagen = models.ImageField(default='null')
    cont_pos = models.IntegerField(default=0)
    cont_neg = models.IntegerField(default=0)
    contador_c = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo

class Comentario_RN(models.Model):
    aport = models.ForeignKey(RecursoN, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

class Votos_RN(models.Model):
    aporte = models.ForeignKey(RecursoN, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    voto_positivo = models.IntegerField(default='0')
    voto_negativo = models.IntegerField(default='0')


class Aemet(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    municipio = models.CharField(max_length=20)
    provincia = models.CharField(max_length=20)
    prediccion = models.TextField()
    copy = models.CharField(max_length=50)
    num = models.IntegerField()
    cont_pos = models.IntegerField(default=0)
    cont_neg = models.IntegerField(default=0)
    contador_c = models.IntegerField(default=0)

    def __str__(self):
        return self.municipio


class Aportacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    url = models.CharField(max_length=500)
    titulo = models.CharField(max_length=150)


class Youtube(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    url = models.CharField(max_length=500)
    titulo = models.CharField(max_length=150)
    autor = models.CharField(max_length=150, default='null')
    contenido = models.TextField()
    cont_pos = models.IntegerField(default=0)
    cont_neg = models.IntegerField(default=0)
    contador_c = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo


class Wikipedia(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo = models.TextField()
    contenido = models.TextField()
    imagen = models.ImageField(default='null')
    copy = models.CharField(max_length=150, default='null')
    cont_pos = models.IntegerField(default=0)
    cont_neg = models.IntegerField(default=0)
    contador_c = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo


class Comentario_Y(models.Model):
    aport_video = models.ForeignKey(Youtube, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)


class Comentario_W(models.Model):
    aport_articulo = models.ForeignKey(Wikipedia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)


class Comentario_A(models.Model):
    aport_prediccion = models.ForeignKey(Aemet, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)


class Votos_Y(models.Model):
    aporte = models.ForeignKey(Youtube, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    voto_positivo = models.IntegerField(default='0')
    voto_negativo = models.IntegerField(default='0')


class Votos_W(models.Model):
    aporte = models.ForeignKey(Wikipedia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    voto_positivo = models.IntegerField(default='0')
    voto_negativo = models.IntegerField(default='0')


class Votos_A(models.Model):
    aporte = models.ForeignKey(Aemet, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    voto_positivo = models.IntegerField(default='0')
    voto_negativo = models.IntegerField(default='0')

proyectofinal/lovisto/forms.py
from django import forms
from .models import  Aportacion, Comentario_Y,Comentario_A,Comentario_W, Comentario_RN

class AportacionForm(forms.ModelForm):
    class Meta:
        model = Aportacion
        fields = ('titulo', 'url',)

class ComentarioRNForm(forms.ModelForm):
    class Meta:
        model = Comentario_RN
        fields = ('comentario',)


class ComentarioYForm(forms.ModelForm):
    class Meta:
        model = Comentario_Y
        fields = ('comentario',)

class ComentarioWForm(forms.ModelForm):
    class Meta:
        model = Comentario_W
        fields = ('comentario',)

class ComentarioAForm(forms.ModelForm):
    class Meta:
        model = Comentario_A
        fields = ('comentario',)

proyectofinal/lovisto/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .forms import AportacionForm, ComentarioYForm, ComentarioAForm, ComentarioWForm, ComentarioRNForm
from .models import Usuario, Youtube, Wikipedia, Aemet, Aportacion, \
    Comentario_W, Comentario_A, Comentario_Y, \
    Votos_Y, Votos_W, Votos_A, RecursoN, Votos_RN, Comentario_RN
import json
import urllib.request
import urllib.parse
from .wikipedia_parser import Wikipedia_Channel
from .aemet_parser import Aemet_Channel
from bs4 import BeautifulSoup


def index(request):
    """Función principal, en la cual extremos toda la información que queremos de las aportaciones
    que realizan los usuarios.En primer lugar, recibimos un POST del formulario para la aportación,
    y analizamos el action del POST, si es Positivo o Negativo,nos encargamos de los votos para cada
     aportación, si el action es aportacion, tratamos de extaer la información."""

    form = AportacionForm(request.POST)
    if request.method == "POST":
        action = request.POST['action']
        if action == "Positivo" or action == "Negativo":
            if request.POST['youtub'] == "True":
                votos_Y(request)
            elif request.POST['wikipedi'] == "True":
                votos_W(request)
            elif request.POST['aeme'] == "True":
                votos_A(request)
            elif request.POST['recurn'] == "True":
                votos_RN(request)
        elif action == "aportacion":
            if form.is_valid():
                titulo = request.POST['titulo']
                url = request.POST['url']
                if not url.startswith('https://') and not url.startswith('http://'):
                    url = 'https://' + url
                usuario = Usuario.objects.get(usuario=request.user.username)
                contenido = Aportacion(titulo=titulo, url=url, usuario=usuario)
                # Tenemos tres recursos reconocidos, debemos conocer de cual se trata la aportación
                sitio = urllib.parse.unquote(url.split('/')[2])
                if sitio == 'www.youtube.com' or sitio == 'youtube.com':
                    try:
                        # Para youtube extraemos la información de un doc en formato JSON
                        patron = "https://www.youtube.com/oembed?format=json&url="
                        url_json = patron + url
                        with urllib.request.urlopen(url_json) as json_doc:
                            json_str = json_doc.read().decode(encoding="ISO-8859-1")
                            youtube_json = json.loads(json_str)
                        video_emb = urllib.parse.unquote(youtube_json["html"].split('"')[5])
                        # Guardamos toda la información extraida
                        y = Youtube(usuario=usuario, url=url, titulo=youtube_json["title"],
                                    autor=youtube_json["author_name"], contenido=video_emb)
                        contenido.save()
                        y.save()
                    except:
                        context = {'usuario': usuario}
                        return render(request,'noaporte.html', context)

                elif sitio == 'es.wikipedia.org':
                    '''Para cada articulo de wikipedia, extremos la imagen de un doc JSON 
                     y el contenido de un XML con wikipedia_parser'''
                    try:
                        articulo = urllib.parse.unquote((url.split('/')[4]))
                        url_json = 'https://es.wikipedia.org/w/api.php?action=query&titles=' + articulo \
                                   + '&prop=pageimages&format=json&pithumbsize=100'
                        with urllib.request.urlopen(url_json) as json_doc:
                            json_str = json_doc.read().decode(encoding="ISO-8859-1")
                            wikipedia_json = json.loads(json_str)
                            num = str(wikipedia_json["query"]["pages"])
                            num = urllib.parse.unquote(num.split("'")[1])
                        imagen = wikipedia_json["query"]["pages"][num]["thumbnail"]["source"]

                        url_xml = 'https://es.wikipedia.org/w/api.php?action=query&format=xml&titles=' + articulo \
                                  + '&prop=extracts&exintro&explaintext'
                        xmlStream = urllib.request.urlopen(url_xml)
                        channel = Wikipedia_Channel(xmlStream)
                        data = channel.articulo()[:400]
                        copy = "https://es.wikipedia.org/wiki/"+articulo
                        # Guardamos toda la información extraida
                        contenido.save()
                        w = Wikipedia(usuario=usuario, contenido=data, imagen=imagen, copy=copy, titulo=articulo)
                        w.save()
                    except:
                        context = {'usuario': usuario}
                        return render(request, 'noaporte.html', context)

                elif sitio == 'www.aemet.es' or sitio == 'aemet.es':
                    try:
                        # Debemos conocer el identificador del municipio
                        num = urllib.parse.unquote(url.split('-id')[1])
                        # Extraemos toda la info de un doc XML con aemet_parser
                        url_xml = 'https://www.aemet.es/xml/municipios/localidad_' + num + '.xml'
                        xmlStream = urllib.request.urlopen(url_xml)
                        channel = Aemet_Channel(xmlStream)
                        data = channel.prediccion()
                        municipio = data[0]['ciudad']
                        provincia = data[0]['provincia']
                        copy = data[0]['copyright']
                        prediccion = ""
                        for dias in data:
                            prediccion += "<li>" + dias['dia'] + "." + " Temperatura: " + dias['temp_max'] \
                                          + "/" + dias['temp_min'] + " Sensación: " + dias['sens_max'] \
                                          + "/" + dias['sens_min'] + "." + " Humedad relativa: " + dias['hum_max'] \
                                          + "/" + dias['hum_min'] + "</li>"
                        # Guardamos toda la información extraida
                        contenido.save()
                        a = Aemet(usuario=usuario, municipio=municipio, provincia=provincia,
                                  copy=copy, prediccion=prediccion, num=num)
                        a.save()
                    except:
                        context = {'usuario': usuario}
                        return render(request, 'noaporte.html', context)

                else:
                    try:
                        htmlStream = urllib.request.urlopen(url)
                        soup = BeautifulSoup(htmlStream, 'html.parser')
                        titulo = soup.find("meta", property="og:title", content=True)
                        titulo = titulo['content']
                        imagen = soup.find("meta", property="og:image", content=True)
                        imagen = imagen['content']
                        contenido.save()
                        n = RecursoN(usuario=usuario, titulo=titulo, imagen=imagen,)
                        n.save()
                    except:
                        context = {'usuario': usuario}
                        return render(request, 'noaporte.html', context)



                    
        elif action == "Modo oscuro":
            usuario = Usuario.objects.get(usuario=request.user.username)
            usuario.tema = "oscuro"
            usuario.save()
        elif action == "Modo claro":
            usuario = Usuario.objects.get(usuario=request.user.username)
            usuario.tema = "claro"
            usuario.save()

        return redirect('/lovisto/')

    else:
        # Si lo que recibimos es un GET, nos almacenamos en variables, toda la lista de aportaciones para cada recurso
        listado_contenidos = Youtube.objects.all()[:10]
        listado_contenidos_w = Wikipedia.objects.all()[:10]
        listado_contenidos_a = Aemet.objects.all()[:10]
        listado_recurso_no = RecursoN.objects.all()[:10]
        listado_votos_y = []
        listado_votos_w = []
        listado_votos_a = []
        listado_votos_rn = []
        usuario = ""
        cinco_aport =""
        if request.user.is_authenticated:
            # si el usuario esta autenticado, hacemos los mismo pero con los votos
            usuario = Usuario.objects.get(usuario=request.user.username)
            listado_votos_y = votosy(usuario.votos_y_set.all())
            listado_votos_w = votosw(usuario.votos_w_set.all())
            listado_votos_a = votosa(usuario.votos_a_set.all())
            listado_votos_rn = votosrn(usuario.votos_rn_set.all())
            cinco_aport = aportaciones(usuario.aportacion_set.all())

        context = {'form': form, 'listado_contenidos': listado_contenidos, 'listado_contenidos_w': listado_contenidos_w,
                   'listado_contenidos_a': listado_contenidos_a, 'listado_recurso_no': listado_recurso_no, 'votosyt': listado_votos_y,
                   'votoswk': listado_votos_w, 'votosam': listado_votos_a,'votosrn': listado_votos_rn, 'usuario': usuario,
                   'cinco_aport': cinco_aport}

    if request.GET.get('format') == 'xml':
        return render(request, 'doc_index.xml', context, content_type="text/xml")
    elif request.GET.get('format') == 'json':
        return render(request, 'doc_index.json', context, content_type="text/json")

    return render(request, 'index.html', context)


def votos_Y(request):
    """En esta función, tratamos los votos para las aportaciones de Youtube. En primer lugar, debemos conocer de que
    video se trata y que usuario ha votado. En caso de vota Positivo, ponemos el valor de voto_positivo a 1 y el

proyectofinal/lovisto/templates/aportacion.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
{% if usuario.tema == "oscuro" %}
    <link rel="stylesheet" type="text/css" href="{% static 'lovisto/styles_oscuro.css' %}">
{% elif usuario.tema == "claro" %}
    <link rel="stylesheet" type="text/css" href="{% static 'lovisto/styles_claro.css' %}">
{% endif %}
<div class="container-fluid">
    <div class="row">
      <div class="col">
      {% if youtube %}
        <h2 align="center">YOUTUBE</h2>
          <div class="youtube">
              <p>{{ youtube.titulo }}</p>
              <iframe width="560" height="315" src="{{ youtube.contenido }}"
                      title={{youtube.titulo}} frameborder="0" allow="accelerometer;
                      encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              <p>Autor: {{ youtube.autor }}. &#9755; <a href="{{ youtube.url }}">Video en YouTube</a></p><hr>
              <p><h5>COMENTARIOS</h5>
              {% for comentario  in youtube.comentario_y_set.all %}
                   <p><b><i>Comentario:</i></b>{{ comentario.comentario }}</p>
                   <p><b><i>Usuario: </i></b> {{ comentario.usuario }} </p>
                   <p><b><i>Fecha:</i></b> {{ comentario.fecha }}</p>
              {% endfor %}<br><hr>
              {% if user.is_authenticated %}
               <h4>Hola, {{ user.username }}, puedes añadir tu comentario a esta aportación!</h4>
                <form method="POST">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-outline-info">Guardar &#128450;</button>
                </form>
              {% endif %}
          </div>
    </div>
    </div>
    {% endif %}
    {% if wikipedia %}
    <div class="col">
        <h2 align="center">WIKIPEDIA</h2>
            <div class="wikipedia">
                <p>Artıculo Wikipedia: {{ wikipedia.titulo }}</p>
                <img src="{{ wikipedia.imagen }}">
                <p>{{ wikipedia.contenido }}</p>
                <p><a href="{{ wikipedia.copy }}">Artıculo original</a></p><hr>
                <div class="container">
                    <p><h5>COMENTARIOS</h5>
                    {% for comentario  in wikipedia.comentario_w_set.all %}
                      <p><b><i>Comentario:</i></b> {{ comentario.comentario }}</p>
                       <p><b><i>Usuario: </i></b> {{ comentario.usuario }} </p>
                       <p><b><i>Fecha:</i></b>  {{ comentario.fecha }}</p>
                  {% endfor %}
                </div><br><hr>
              {% if user.is_authenticated %}
               <h4>Hola, {{ user.username }}, puedes añadir tu comentario a esta aportación!</h4>

                <form method="POST">{% csrf_token %}
                    {{ form.as_p }}
                      <button type="submit" class="save btn btn-outline-info">Guardar &#128450;</button>
                </form>
              {% endif %}
            </div>
      </div>
    {% endif %}
    {% if aemet %}
     <div class="col">
        <h2 align="center">PREVISIÓN ATMOSFÉRICA</h2>
          <div class="aemet">
           <p>Datos AEMET para {{ aemet.municipio }} ({{ aemet.provincia }})</p>
            {{ aemet.prediccion|safe }}<br>
           <p>{{ aemet.copy }} Página original en AEMET</p><hr>
              <div class="container">
              <p><h5>COMENTARIOS</h5>
              {% for comentario  in aemet.comentario_a_set.all %}
                <p><b><i>Comentario:</i></b> {{ comentario.comentario }}</p>
               <p><b><i>Usuario: </i></b> {{ comentario.usuario }} </p>
               <p><b><i>Fecha:</i></b>  {{ comentario.fecha }}</p>
              {% endfor %}
              </div><br><hr>
              {% if user.is_authenticated %}
               <h4>Hola, {{ user.username }}, puedes añadir tu comentario a esta aportación!</h4>

                <form method="POST">{% csrf_token %}
                    {{ form.as_p }}
                     <button type="submit" class="save btn btn-outline-info">Guardar &#128450;</button>
                </form>
              {% endif %}
          </div>
      </div>
    {% endif %}
</div>
    {% if recurson %}
        <h2 align="center">Recurso no reconocido</h2>
          <div class="recurso">
              <div class="container-fluid">
              <p>{{ recurson.titulo }}</p>
              <img src="{{recurson.imagen}}" width="100" height="100"><hr>
                  <p><h5>COMENTARIOS</h5>
              {% for comentario in recurson.comentario_rn_set.all %}
                   <p><b><i>Comentario:</i></b>{{ comentario.comentario }}</p>
                   <p><b><i>Usuario: </i></b> {{ comentario.usuario }} </p>
                   <p><b><i>Fecha:</i></b> {{ comentario.fecha }}</p>
              {% endfor %}
                 <br><hr>
              {% if user.is_authenticated %}
               <h4>Hola, {{ user.username }}, puedes añadir tu comentario a esta aportación!</h4>
                <form method="POST">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-outline-info">Guardar &#128450;</button>
                </form>
              {% endif %}
              {% endif %}
                   </div>
          </div>
</body>
</html>
{% endblock %}

proyectofinal/lovisto/templates/aportaciones.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
{% if usuario.tema == "oscuro" %}
    <link rel="stylesheet" type="text/css" href="{% static 'lovisto/styles_oscuro.css' %}">
{% elif usuario.tema == "claro" %}
    <link rel="stylesheet" type="text/css" href="{% static 'lovisto/styles_claro.css' %}">
{% endif %}

<body>
        <div class="listado">
            <div class="container-fluid">
                <div class="row" align="center">
                    <div class="col">
                    <div class="card-header"><h3>Listado de las aportaciones realizadas a LO VISTO</h3></div>
                      {% for aportacion in aportaciones %}
                      <p>&#10140;  {{ aportacion.titulo }}:  <a href="{{ aportacion.url }}">Click aquí!</a></p>
                      {% endfor %}
                        </div>
                </div>
          </div>
        </div>
<div class="container-fluid">
    <div class="row">
        <div class="col" align="center">
            <h4>Obtener documento en formato XML </h4>
                &#128317;
            <h3><a href="aportaciones?format=xml">XML</a></h3>
        </div>
        <div class="col" align="center">
            <h4>Obtener documento en formato JSON</h4>
                &#128317;
            <h3><a href="aportaciones?format=json">JSON</a></h3>
        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

proyectofinal/lovisto/templates/usuario.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="card-header"><h5 align="center"> <b>PERFIL DE  {{ usuario }}</b></h5></div>
     <div class="row">
         <div class="col" align="center">
             <h4><b>Aportaciones generales </b></h4>
              {% for aporte in cinco_aport %}
                 <p><b>Titulo:</b> {{ aporte.titulo }}</p>
                 <p><b>Aporte: </b> <a href="{{ aporte.url }}">{{ aporte.url }}</a></p>
             {% endfor %}
         </div>
     </div><hr>
     <div class="row">
         <div class="col" align="center">
             <h4><b>Aportaciones realizadas por {{ usuario }} a YOUTUBE</b></h4>
              {% for aporte in usuario.youtube_set.all %}
                 <p><b>Titulo de la aportación realizada:</b> {{ aporte.titulo }}</p>
                  <p><b>Aporte: </b> <a href="{{ aporte.url }}">{{ aporte.url }}</a></p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Comentarios realizados por {{ usuario }}</b></h4>
              {% for comentario in usuario.comentario_y_set.all %}
             <p><b>Aportación comentada:</b> {{ comentario.aport_video }}</p>
                    <p><b> Comentario: </b> {{ comentario.comentario }} </p>
                    <p><b> Fecha:</b>  {{ comentario.fecha }}</p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Votaciones realizadas por  {{ usuario }}</b></h4>
              {% for voto in usuario.votos_y_set.all %}
                  <p><b> Aportación votada:</b>  {{ voto.aporte }}</p>
                    <p><b> Voto:</b>  {% if voto.voto_positivo %}
                                &#10004;
                            {% else %}
                                &#10007;
                        {% endif %}</p>
             {% endfor %}
         </div>
     </div><hr>
    <div class="row">
         <div class="col" align="center">
             <h4><b>Aportaciones realizadas por  {{ usuario }} a WIKIPEDIA</b></h4>
              {% for aporte in usuario.wikipedia_set.all %}
                  <p><b>Titulo de la aportación realizada</b>: {{ aporte.titulo }}</p>
                    <p> <b>Aportación: </b>{{ aporte.contenido }} </p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Comentarios realizados por  {{ usuario }}</b></h4>
              {% for comentario in usuario.comentario_w_set.all %}
                  <p><b> Aportación comentada: </b> {{ comentario.aport_articulo }}</p>
                    <p> <b> Comentario: </b> {{ comentario.comentario }} </p>
                    <p><b> Fecha:</b>  {{ comentario.fecha }}</p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Votaciones realizadas por {{ usuario }}</b></h4>
              {% for voto in usuario.votos_w_set.all %}
                  <p><b> Aportación votada:</b>  {{ voto.aporte }}</p>
                    <p><b> Voto:</b>  {% if voto.voto_positivo %}
                                &#10004;
                            {% else %}
                                &#10007;
                        {% endif %}</p>
             {% endfor %}
         </div>
    </div><hr>
    <div class="row">
             <div class="col" align="center">
                 <h4><b> Aportaciones realizadas por {{ usuario }} a AEMET</b></h4>
                  {% for aporte in usuario.aemet_set.all %}
                        <p><b>  Municipio:</b>  {{ aporte.municipio }} </p>
                        <p><b> Predicción:</b>  {{ aporte.prediccion|safe }}</p>
                 {% endfor %}
             </div>
             <div class="col" align="center">
                 <h4><b> Comentarios realizados por {{ usuario }}</b> </h4>
                  {% for comentario in usuario.comentario_a_set.all %}
                      <p><b> Aportación comentada:</b>  {{ comentario.aport_prediccion }}</p>
                        <p><b>  Comentario: </b> {{ comentario.comentario }} </p>
                        <p><b> Fecha:</b>  {{ comentario.fecha }}</p>
                 {% endfor %}
             </div>
             <div class="col" align="center">
                 <h4><b> Votaciones realizadas por  {{ usuario }}</b> </h4>
                  {% for voto in usuario.votos_a_set.all %}
                      <p><b> Aportación votada:</b>  {{ voto.aporte }}</p>
                        <p><b> Voto:</b>  {% if voto.voto_positivo %}
                                    &#10004;
                                {% else %}
                                    &#10007;
                            {% endif %}</p>
                 {% endfor %}
             </div>
    </div><hr>
    <div class="row">
         <div class="col" align="center">
             <h4><b>Aportaciones realizadas por {{ usuario }} a Recursos no reconocidos</b></h4>
              {% for aporte in usuario.recurson_set.all %}
                 <p><b>Titulo de la aportación realizada:</b> {{ aporte.titulo }}</p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Comentarios realizados por {{ usuario }}</b></h4>
              {% for comentario in usuario.comentario_rn_set.all %}
             <p><b>Aportación comentada:</b> {{ comentario.aport }}</p>
                    <p><b> Comentario: </b> {{ comentario.comentario }} </p>
                    <p><b> Fecha:</b>  {{ comentario.fecha }}</p>
             {% endfor %}
         </div>
         <div class="col" align="center">
             <h4><b>Votaciones realizadas por  {{ usuario }}</b></h4>
              {% for voto in usuario.votos_rn_set.all %}
                  <p><b> Aportación votada:</b>  {{ voto.aporte }}</p>
                    <p><b> Voto:</b>  {% if voto.voto_positivo %}
                                &#10004;
                            {% else %}
                                &#10007;
                        {% endif %}</p>
             {% endfor %}
         </div>
     </div>
</div><hr>
<div class="container-fluid">
    <div class="row">
    <div class="col" align="center">
        <h4>Obtener documento en formato XML </h4>
            &#128317;
        <h4><a href="?format=xml">XML</a></h4>
    </div>
    <div class="col" align="center">
        <h4>Obtener documento en formato JSON</h4>
            &#128317;
        <h4><a href="?format=json">JSON</a></h4>
    </div>
    </div>
</div>

{% endblock %}